// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {appstate} from '../models';
import {config} from '../models';

export function GetAppState():Promise<appstate.AppState>;

export function GetConfig():Promise<config.AppConfig>;

export function SaveConfig(arg1:config.AppConfig):Promise<void>;
