// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {parser} from '../models';
import {browser} from '../models';
import {diagnostics} from '../models';
import {appstate} from '../models';
import {config} from '../models';
import {credentials} from '../models';
import {monitor} from '../models';
import {storage} from '../models';
import {auth} from '../models';

export function AutoFillCredentials(arg1:string,arg2:string):Promise<void>;

export function CancelDownload():Promise<void>;

export function CheckLoginStatus():Promise<boolean>;

export function CheckNow():Promise<parser.ParsedResults>;

export function ClearResultsHistory():Promise<void>;

export function ClearSession():Promise<void>;

export function CloseBrowser():Promise<void>;

export function DeleteCredentials():Promise<void>;

export function DeleteKernel():Promise<void>;

export function DetectBrowsers():Promise<Array<browser.BrowserInfo>>;

export function DownloadBrowserKernel():Promise<void>;

export function ExportDiagnosticReport(arg1:string):Promise<void>;

export function GenerateDiagnosticReport():Promise<diagnostics.DiagnosticReport>;

export function GetAppState():Promise<appstate.AppState>;

export function GetBestBrowser():Promise<browser.BrowserInfo>;

export function GetConfig():Promise<config.AppConfig>;

export function GetCredentials():Promise<credentials.Credentials>;

export function GetCurrentResults():Promise<parser.ParsedResults>;

export function GetDefaultDiagnosticPath():Promise<string>;

export function GetDiagnosticReportAsString():Promise<string>;

export function GetDownloadProgress():Promise<browser.DownloadProgress>;

export function GetKernelPath():Promise<string>;

export function GetMonitorStatus():Promise<monitor.MonitorStatus>;

export function GetResultsHistory():Promise<Array<storage.HistoryItem>>;

export function GetSession():Promise<auth.Session>;

export function HasCredentials():Promise<boolean>;

export function IsKernelDownloaded():Promise<boolean>;

export function NavigateToTarget():Promise<void>;

export function PauseMonitoring():Promise<void>;

export function ResumeMonitoring():Promise<void>;

export function SaveConfig(arg1:config.AppConfig):Promise<void>;

export function SaveCredentials(arg1:string,arg2:string):Promise<void>;

export function SendNotification(arg1:string,arg2:string):Promise<void>;

export function StartLoginFlow():Promise<void>;

export function StartMonitoring():Promise<void>;

export function StopMonitoring():Promise<void>;

export function TestBarkNotification(arg1:string):Promise<void>;

export function ValidateSession():Promise<boolean>;
