// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {browser} from '../models';
import {appstate} from '../models';
import {config} from '../models';
import {auth} from '../models';

export function AutoFillCredentials(arg1:string,arg2:string):Promise<void>;

export function CheckLoginStatus():Promise<boolean>;

export function ClearSession():Promise<void>;

export function CloseBrowser():Promise<void>;

export function DetectBrowsers():Promise<Array<browser.BrowserInfo>>;

export function GetAppState():Promise<appstate.AppState>;

export function GetBestBrowser():Promise<browser.BrowserInfo>;

export function GetConfig():Promise<config.AppConfig>;

export function GetSession():Promise<auth.Session>;

export function NavigateToTarget():Promise<void>;

export function SaveConfig(arg1:config.AppConfig):Promise<void>;

export function StartLoginFlow():Promise<void>;

export function ValidateSession():Promise<boolean>;
