// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoFillCredentials(arg1, arg2) {
  return window['go']['main']['App']['AutoFillCredentials'](arg1, arg2);
}

export function CheckLoginStatus() {
  return window['go']['main']['App']['CheckLoginStatus']();
}

export function ClearSession() {
  return window['go']['main']['App']['ClearSession']();
}

export function CloseBrowser() {
  return window['go']['main']['App']['CloseBrowser']();
}

export function DetectBrowsers() {
  return window['go']['main']['App']['DetectBrowsers']();
}

export function GetAppState() {
  return window['go']['main']['App']['GetAppState']();
}

export function GetBestBrowser() {
  return window['go']['main']['App']['GetBestBrowser']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetSession() {
  return window['go']['main']['App']['GetSession']();
}

export function NavigateToTarget() {
  return window['go']['main']['App']['NavigateToTarget']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartLoginFlow() {
  return window['go']['main']['App']['StartLoginFlow']();
}

export function ValidateSession() {
  return window['go']['main']['App']['ValidateSession']();
}
