// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoFillCredentials(arg1, arg2) {
  return window['go']['main']['App']['AutoFillCredentials'](arg1, arg2);
}

export function CancelDownload() {
  return window['go']['main']['App']['CancelDownload']();
}

export function CheckLoginStatus() {
  return window['go']['main']['App']['CheckLoginStatus']();
}

export function CheckNow() {
  return window['go']['main']['App']['CheckNow']();
}

export function ClearResultsHistory() {
  return window['go']['main']['App']['ClearResultsHistory']();
}

export function ClearSession() {
  return window['go']['main']['App']['ClearSession']();
}

export function CloseBrowser() {
  return window['go']['main']['App']['CloseBrowser']();
}

export function DeleteCredentials() {
  return window['go']['main']['App']['DeleteCredentials']();
}

export function DeleteKernel() {
  return window['go']['main']['App']['DeleteKernel']();
}

export function DetectBrowsers() {
  return window['go']['main']['App']['DetectBrowsers']();
}

export function DownloadBrowserKernel() {
  return window['go']['main']['App']['DownloadBrowserKernel']();
}

export function ExportDiagnosticReport(arg1) {
  return window['go']['main']['App']['ExportDiagnosticReport'](arg1);
}

export function GenerateDiagnosticReport() {
  return window['go']['main']['App']['GenerateDiagnosticReport']();
}

export function GetAppState() {
  return window['go']['main']['App']['GetAppState']();
}

export function GetBestBrowser() {
  return window['go']['main']['App']['GetBestBrowser']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCredentials() {
  return window['go']['main']['App']['GetCredentials']();
}

export function GetCurrentResults() {
  return window['go']['main']['App']['GetCurrentResults']();
}

export function GetDefaultDiagnosticPath() {
  return window['go']['main']['App']['GetDefaultDiagnosticPath']();
}

export function GetDiagnosticReportAsString() {
  return window['go']['main']['App']['GetDiagnosticReportAsString']();
}

export function GetDownloadProgress() {
  return window['go']['main']['App']['GetDownloadProgress']();
}

export function GetKernelPath() {
  return window['go']['main']['App']['GetKernelPath']();
}

export function GetMonitorStatus() {
  return window['go']['main']['App']['GetMonitorStatus']();
}

export function GetResultsHistory() {
  return window['go']['main']['App']['GetResultsHistory']();
}

export function GetSession() {
  return window['go']['main']['App']['GetSession']();
}

export function HasCredentials() {
  return window['go']['main']['App']['HasCredentials']();
}

export function IsKernelDownloaded() {
  return window['go']['main']['App']['IsKernelDownloaded']();
}

export function NavigateToTarget() {
  return window['go']['main']['App']['NavigateToTarget']();
}

export function PauseMonitoring() {
  return window['go']['main']['App']['PauseMonitoring']();
}

export function ResumeMonitoring() {
  return window['go']['main']['App']['ResumeMonitoring']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveCredentials(arg1, arg2) {
  return window['go']['main']['App']['SaveCredentials'](arg1, arg2);
}

export function SendNotification(arg1, arg2) {
  return window['go']['main']['App']['SendNotification'](arg1, arg2);
}

export function StartLoginFlow() {
  return window['go']['main']['App']['StartLoginFlow']();
}

export function StartMonitoring() {
  return window['go']['main']['App']['StartMonitoring']();
}

export function StopMonitoring() {
  return window['go']['main']['App']['StopMonitoring']();
}

export function TestBarkNotification(arg1) {
  return window['go']['main']['App']['TestBarkNotification'](arg1);
}

export function ValidateSession() {
  return window['go']['main']['App']['ValidateSession']();
}
